// Generated by npm run configure from config/project.json. Do not hand-edit.
const config = {
  EMAIL_VERIFICATION_ENABLED: true,
  CLOUDBASE_ENV: "cloud1-d7gifgdpb8ad0ab8e",
  APPID: "wxba2bcb0c71a5f33d",
  APP_NAME: "LynkU",
  CLOUDBASE_DEBUG: false,
} as const

export default config
