import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { validateLegalMetadata } from './legal-metadata.mjs'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')

export function validateProjectConfig(value) {
  const keys = ['name', 'appId', 'cloudEnvironment', 'baseLibrary', 'emailVerificationEnabled', 'debug', 'legal']
  if (!value || typeof value !== 'object' || Array.isArray(value)
    || Object.keys(value).some(key => !keys.includes(key))
    || keys.some(key => !Object.hasOwn(value, key))) throw new Error('Invalid public project configuration keys')
  if (typeof value.name !== 'string' || !/^[A-Za-z][A-Za-z0-9 -]{0,39}$/.test(value.name)) throw new Error('Invalid project name')
  if (typeof value.appId !== 'string' || !/^wx[0-9a-f]{16}$/.test(value.appId)) throw new Error('Invalid WeChat AppID')
  if (typeof value.cloudEnvironment !== 'string' || !/^[a-z][a-z0-9-]{3,63}$/.test(value.cloudEnvironment)) throw new Error('Invalid CloudBase environment')
  if (typeof value.baseLibrary !== 'string' || !/^\d+\.\d+\.\d+$/.test(value.baseLibrary)) throw new Error('Invalid base library version')
  if (typeof value.emailVerificationEnabled !== 'boolean' || typeof value.debug !== 'boolean') throw new Error('Feature flags must be booleans')
  validateLegalMetadata(value.legal)
  return value
}

export function configureProject(directory, checkOnly = false) {
  const read = relative => JSON.parse(fs.readFileSync(path.join(directory, relative), 'utf8'))
  const config = validateProjectConfig(read('config/project.json'))
  const project = read('project.config.json')
  const cloud = read('cloudbaserc.json')
  const client = `// Generated by npm run configure from config/project.json. Do not hand-edit.\nconst config = {\n  EMAIL_VERIFICATION_ENABLED: ${config.emailVerificationEnabled},\n  CLOUDBASE_ENV: ${JSON.stringify(config.cloudEnvironment)},\n  APPID: ${JSON.stringify(config.appId)},\n  APP_NAME: ${JSON.stringify(config.name)},\n  CLOUDBASE_DEBUG: ${config.debug},\n} as const\n\nexport default config\n`
  const desiredProject = { ...project, appid: config.appId, projectname: config.name, libVersion: config.baseLibrary,
    miniprogramRoot: 'apps/miniprogram/', srcMiniprogramRoot: 'apps/miniprogram/', cloudfunctionRoot: 'dist/cloudfunctions/' }
  const names = ['anonymous', 'avatar_01', 'avatar_02', 'avatar_03', 'avatar_04']
  const originalPaths = names.map(name => `assets/avatar/${name}.png`)
  const runtimePaths = names.map(name => `assets/avatar/runtime/${name}.png`)
  const pack = project.packOptions || {}
  desiredProject.packOptions = { ...pack,
    ignore: [...(pack.ignore || []).filter(item => !originalPaths.includes(item.value)), ...originalPaths.map(value => ({ type: 'file', value }))],
    include: [...(pack.include || []).filter(item => !runtimePaths.includes(item.value)), ...runtimePaths.map(value => ({ type: 'file', value }))],
  }
  const desiredCloud = { ...cloud, envId: config.cloudEnvironment, functionRoot: 'dist/cloudfunctions' }
  const json = value => JSON.stringify(value, null, 2) + '\n'
  const outputs = [
    ['project.config.json', json(desiredProject)],
    ['cloudbaserc.json', json(desiredCloud)],
    ['apps/miniprogram/config.ts', client],
  ]
  // Validate all drift before writing any file. Check mode never repairs errors silently.
  const changed = outputs.filter(([relative, value]) => fs.readFileSync(path.join(directory, relative), 'utf8').replace(/\r\n/g, '\n') !== value)
  if (checkOnly && changed.length) throw new Error(`Configuration drift: ${changed.map(([file]) => file).join(', ')}. Run npm run configure.`)
  if (!checkOnly) for (const [relative, value] of changed) fs.writeFileSync(path.join(directory, relative), value)
  return config
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  configureProject(root, process.argv.includes('--check'))
  console.log(process.argv.includes('--check') ? 'Public configuration matches the single manifest.' : 'LynkU project configuration generated. No cloud resources changed.')
}
